package org.firstinspires.ftc.teamcode.layer;

import java.util.Collections;
import java.util.Iterator;

import org.firstinspires.ftc.teamcode.task.Task;

/**
 * Convenience base class for all layers that map each accepted task to only one subtask.
 * Similar to {@link QueuedLayer}, but only generates one task instead of a queue.
 */
public abstract class FunctionLayer implements Layer {
    /**
     * Whether {@link #subtask} has been emitted yet.
     */
    private boolean emittedSubtask;
    /**
     * The next subtask to emit, generated by calling {@link #map} on the last accepted task.
     */
    private Task subtask;

    /**
     * Constructs a FunctionLayer.
     */
    protected FunctionLayer() {
        emittedSubtask = true;
        subtask = null;
    }

    @Override
    public boolean isTaskDone() {
        return emittedSubtask;
    }

    @Override
    public Iterator<Task> update(Iterable<Task> completed) {
        if (emittedSubtask) {
            throw new IllegalStateException("FunctionLayer " + getClass().getName()
                + " updated without new subtask.");
        }
        emittedSubtask = true;
        return Collections.singleton(subtask).iterator();
    }

    @Override
    public void acceptTask(Task task) {
        subtask = map(task);
        if (subtask == null) {
            throw new NullPointerException("FunctionLayer " + getClass().getName()
                + " returned null from mapping function.");
        }
        emittedSubtask = false;
    }

    /**
     * Maps an accepted task to a subtask.
     * @param task The accepted task.
     * @return The subtask generated from the accepted task.
     */
    protected abstract Task map(Task task);
}
